language: java

jdk: openjdk8

install: true
script: mvn clean package -DskipTests=true -Dspring.profiles.active=local
services:
  - docker
before_install:
  - chmod +x mvnw
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jdk-alpine

after_success:
  - export IMAGE_NAME=canavdan/gagful-api
  - export TAG=1.0
  - docker tag $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG