version: '3'
services:
  mysql-db:
    image: mysql:5.6
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dbexa
      - MYSQL_PASSWORD=admin
    restart: always

  gagful:
    container_name: gagful
    image: gagful:1.0
    links:
      - mysql-db
    environment:
      - DATABASE_NAME=dbexa
      - DATABASE_PORT=3306
      - DATABASE_HOST=mysql-db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=admin
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    restart: always
